language: node_js
jobs:
  include:
    - os: osx
      osx_image: xcode11.2
install: true
script:
  python2   --version || true
  python2.7 --version || true
  python3   --version || true
  python3.5 --version || true
  python3.6 --version || true
  python3.7 --version || true
  python3.8 --version || true
