language: node_js
jobs:
  include:
    - os: osx
      osx_image: xcode11.2
install: true
script:
  - python2.7 --version ; python2.7 -m pip --version
  - python3   --version ; python3   --version
  - pyenv install --list
